
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: applythis
spec:
  homepage: https://github.com/turkenh/kubectl-applythis
  shortDescription: Directly create/apply yaml files without writing into file.
  version: v0.1.0
  description: |
    A simple kubectl plugin that allows to create/apply Kubernetes resources directly from editor.
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    uri: https://github.com/turkenh/kubectl-applythis/releases/download/v0.1.0/kubectl-applythis-v0.1.0.tar.gz
    sha256: 1429a90224b435e7185804022d1840c0ce72c05bacedf162982059b2ff7440d4
    bin: kubectl-applythis/applythis
    files:
    - from: '*'
      to: .